version: '3'

services:

  blockbook:
    image: johntonny2019/blockbook-vircle:v1.0.2
    restart: always
    container_name: 'blockbook-vircle'
    environment:
      - RPC_USER: "chain"
      - RPC_PASS: "999000" 
      - RPC_HOST: "172.17.0.1" 
      - RPC_PORT: 9092 
      - RPC_HTTP: "http" 
      - NEVM_HTTP: "http" 
      - NEVM_HOST: "172.17.0.1" 
      - NEVM_PORT: 4000 
      - BLOCKBOOK_PORT: 9130 
      - WORKERS: 4
    volumes:
      - /root/blockbook/data:/home/blockbook/data
    ports:
      - 9130:9130
